### PR TITLE
Feature/90 loading wheels in storage window

### PR DESCRIPTION
**Pull request by 0x6431346e**
## What changed?
- Added spinner to StorageWindow and DetailsWindow
- Added loading state to Download + Remove buttons

### CODE REVIEW

**Comment by 0x6431346e** [comment]
@koalalorenzo Should we add this loading spinner to all windows? Please test and let me know :)

**Comment by koalalorenzo** [comment]
Uhm, I am checking, it looks good.

Could we add also a spinning wheel in the footer? Sometimes when you have a lot of files it takes some time and the list is empty, the footer shows "connected" but it is actually waiting for the API to resolve.

**Comment by 0x6431346e** [comment]
@koalalorenzo How about having the spinner on top of the table instead of the footer?

**Comment by koalalorenzo** [comment]
I would prefer it on the footer, as we may use it for status and other information in the future

**Comment by 0x6431346e** [comment]
Makes sense. Now it will say "Connected" after the list is fetched :)

**Pull request merged**
