### PR TITLE
Feature/68 set up auto updater

### PR DESCRIPTION
**Pull request by 0x6431346e**

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Shouldn't we trigger an action when the event `update-available` is fired? Like show a dialog saying "A new version is available!" and two buttons, one for going to github releases page, one for the "remind me next time" ?

**Comment by koalalorenzo** [comment]
here: https://github.com/electron/electron/blob/master/docs/api/auto-updater.md#event-update-available

**Comment by 0x6431346e** [comment]
Only on linux, right?

**Comment by koalalorenzo** [comment]
All of them

**Comment by 0x6431346e** [comment]
But on mac and windows, it will just download the update in the background and install it when the app quits, wouldn't it be confusing to send them to GitHub?

**Comment by koalalorenzo** [comment]
Good point: until I get sorted out the certificate that won’t work, so we should show anyway a message to the user, as the app won’t be installed in background. Does it make senses? What do you think?

**Pull request merged**
